import { loadEnv, log } from '../scripts/lib.mjs';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

loadEnv();

const GEMINI_KEY = process.env.GEMINI_API_KEY || '';

/**
 * Call the OpenAI Chat Completions API.
 * Retries with exponential backoff on 429 (rate limit) and 5xx errors.
 */
export async function chat({ system, user, model = 'gpt-4o', temperature = 0.7, jsonMode = false, maxTokens = 4000 }) {
  const openAIKey = process.env.OPENAI_API_KEY || '';
  if (!openAIKey) throw new Error('OPENAI_API_KEY is required for this stage');
  const body = {
    model,
    messages: [
      { role: 'system', content: system },
      { role: 'user', content: user },
    ],
    temperature,
    max_tokens: maxTokens,
  };
  if (jsonMode) {
    body.response_format = { type: 'json_object' };
  }

  const maxRetries = 3;
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    const res = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${openAIKey}`,
      },
      body: JSON.stringify(body),
    });

    if (res.ok) {
      const data = await res.json();
      const usage = data.usage ? `(${data.usage.prompt_tokens} in / ${data.usage.completion_tokens} out)` : '';
      log('info', `OpenAI ${model}: ${usage}`);
      return data.choices[0].message.content;
    }

    const text = await res.text();

    // Retry on rate limit (429) and server errors (5xx)
    if ((res.status === 429 || res.status >= 500) && attempt < maxRetries) {
      const delay = 2000 * Math.pow(2, attempt); // 2s, 4s, 8s
      log('warn', `OpenAI ${res.status} — retry ${attempt + 1}/${maxRetries} in ${delay}ms`);
      await new Promise((r) => setTimeout(r, delay));
      continue;
    }

    log('error', `OpenAI API error: ${res.status} ${text}`);
    throw new Error(`OpenAI ${res.status}: ${text}`);
  }

  throw new Error('OpenAI: max retries exceeded');
}

/**
 * Generate an image using the Gemini API (experimental image generation).
 */
export async function generateImage(prompt, outputPath) {
  if (!GEMINI_KEY) {
    log('warn', 'Gemini API key not set, skipping image generation');
    return null;
  }

  const res = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp-image-generation:generateContent?key=${GEMINI_KEY}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: { responseModalities: ['Text', 'Image'] },
      }),
    }
  );

  if (!res.ok) {
    const text = await res.text();
    log('error', `Gemini API error: ${res.status} ${text}`);
    return null;
  }

  const data = await res.json();
  const imagePart = data.candidates?.[0]?.content?.parts?.find((p) => p.inlineData);
  if (!imagePart) {
    log('warn', 'No image generated by Gemini');
    return null;
  }

  const imageData = Buffer.from(imagePart.inlineData.data, 'base64');
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, imageData);
  log('info', `Image saved: ${outputPath}`);
  return outputPath;
}
